// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcEJhAF2Z36zryDOxGqNqpIHxMYhdyMgA',
    appId: '1:712396408897:web:b76841c88e1d73fb861ec0',
    messagingSenderId: '712396408897',
    projectId: 'sangkap-snap',
    authDomain: 'sangkap-snap.firebaseapp.com',
    storageBucket: 'sangkap-snap.appspot.com',
    measurementId: 'G-VCFJ7CED2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWI_qbKsttWsiaFaIyazP5xllMUFaMjWI',
    appId: '1:712396408897:android:b3433b716d842392861ec0',
    messagingSenderId: '712396408897',
    projectId: 'sangkap-snap',
    storageBucket: 'sangkap-snap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzC-Mukzww-LbVNdopSL-quj-u9OSmQ5s',
    appId: '1:712396408897:ios:37e45f82cb0f2a91861ec0',
    messagingSenderId: '712396408897',
    projectId: 'sangkap-snap',
    storageBucket: 'sangkap-snap.appspot.com',
    iosBundleId: 'com.example.mainApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzC-Mukzww-LbVNdopSL-quj-u9OSmQ5s',
    appId: '1:712396408897:ios:37e45f82cb0f2a91861ec0',
    messagingSenderId: '712396408897',
    projectId: 'sangkap-snap',
    storageBucket: 'sangkap-snap.appspot.com',
    iosBundleId: 'com.example.mainApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcEJhAF2Z36zryDOxGqNqpIHxMYhdyMgA',
    appId: '1:712396408897:web:52af884cc645a2c2861ec0',
    messagingSenderId: '712396408897',
    projectId: 'sangkap-snap',
    authDomain: 'sangkap-snap.firebaseapp.com',
    storageBucket: 'sangkap-snap.appspot.com',
    measurementId: 'G-9EG0Z30LLX',
  );
}
